plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

version '1.0'
group 'com.pichincha'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.datafaker:datafaker:2.4.2'
    testImplementation 'io.karatelabs:karate-junit5:1.5.1'
}

sourceSets {
    test {
        resources {
            srcDir file('src/test/java')
            exclude '**/*.java'
        }
    }
}

test {
    useJUnitPlatform()

    systemProperty "karate.options", System.properties.getProperty("karate.options")
    systemProperty "karate.env", System.properties.getProperty("karate.env")

    outputs.upToDateWhen { false }
}
